In [2]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler, OneHotEncoder
from sklearn.feature_selection import SelectKBest, f_regression, f_classif

In [7]:
df = pd.read_excel(r"/content/01 covid_toy.xlsx")
display(df.head())

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [9]:
print(df.dtypes)

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [11]:
numeric_columns = df.select_dtypes(include=np.number).columns

In [15]:
print("Numberic Columns:")
print("numeric_columns")

Numberic Columns:
numeric_columns

In [19]:
df["fever"] = pd.to_numeric(df["fever"], errors='coerce')
df["fever"] = df["fever"].fillna(df["fever"].mean())

In [21]:
print(df.isnull().sum())

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [23]:
print(df.isnull().sum())

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [25]:
scaler = MinMaxScaler().set_output(transform="pandas")

scaled_data = scaler.fit_transform(df[numeric_columns])

scaled_data.head()

        age     fever
0  0.696203  0.833333
1  0.278481  0.333333
2  0.468354  0.500000
3  0.329114  0.000000
4  0.759494  0.500000

In [27]:
# Define the target y (has_covid) and features X
y = df["has_covid"]
X = df.drop(columns=["has_covid"])

# Select only numeric features (age, fever)
X_numeric = X.select_dtypes(include=np.number)

# Perform feature selection using f_classif (since target is categorical)
selector = SelectKBest(
    score_func=f_classif,
    k=2
).set_output(transform="pandas")

X_selected = selector.fit_transform(X_numeric, y)

print(X_selected.head())

   age  fever
0   60  103.0
1   27  100.0
2   42  101.0
3   31   98.0
4   65  101.0